// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rankCpp
NumericVector rankCpp(NumericVector x);
RcppExport SEXP easyVerification_rankCpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(rankCpp(x));
    return __result;
END_RCPP
}
// EnsRocaCpp
NumericVector EnsRocaCpp(NumericMatrix ens, NumericMatrix obs);
RcppExport SEXP easyVerification_EnsRocaCpp(SEXP ensSEXP, SEXP obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type ens(ensSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type obs(obsSEXP);
    __result = Rcpp::wrap(EnsRocaCpp(ens, obs));
    return __result;
END_RCPP
}
// rankEnsCpp
NumericVector rankEnsCpp(NumericMatrix ens);
RcppExport SEXP easyVerification_rankEnsCpp(SEXP ensSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type ens(ensSEXP);
    __result = Rcpp::wrap(rankEnsCpp(ens));
    return __result;
END_RCPP
}
